### ISSUE TITLE
Change MBTs on Resounding Thunder to T-55s

### ISSUE THREAD

**Issue by Yin-Yue** [SchwererKonigstiger/Missions#12]
T-72s in the mission need to be replaced with T-55s. One or two T-72s may be left for variety, the current AT situation can /probably/ handle them. AT training is recommended to help alleviate. Will expand further on this issue in the second writeup for supply crates.

**Comment by SchwererKonigstiger** [comment]
I'll swap them out to T-55s/BMPs once I get a chance.

**Comment by SchwererKonigstiger** [comment]
BMPs/BMDs have been added, and infantry squads swapped to Russians on mission that is current with GH.
All heavy armour has been ripped out for the time being.
You may see it again *later*
