### ISSUE TITLE
Operation Resounding Thunder - supply crates

### ISSUE THREAD

**Issue by Yin-Yue** [SchwererKonigstiger/Missions#13]
Supply drops inside the AO are meant to contain various supplies, including (but not limited to?) anti-tank weapons and ammunition.

As of this write-up the planned insertion outfitting for AT will include:
AT-4 HP Launcher for close-range point defense (via www.3commandobrigade.com)
NLAW for close-in targeted and supplementary defense (vanilla and BWMod)
MAAWS HEAT for reloadable AT strikes* (CUP)

*MAAWS gunner will be loaded with two HEAT rockets, a loader kit will be provided to a secondary unit, and will carry 3 more rounds. These two units must remain together at all times.

Certain AT systems will be ineffective to the point of obsoletion, even against T-55s (or IFVs, which, worth noting,  are almost universally designed to provide little to no protection against anything larger than a 12.7mm bullet).
Recommend filling the town supply crates with launchers and ammunition matching any of the ones listed, preferably the MAAWS. Titan Compact/Mini-Spike guided launchers are also recommended for provision (using AT guided rounds, not SACLOS-guided AP), as the MAAWS is the only reloadable launcher that will be carried in. Alternately, a crate of single-shot Javelin Tubes and CLU guidance systems could be provided. QRF unit can insert, dig in, and burn through AT ammunition until enemy armor is routed.

Side note: RPG-7V2 launchers will function, but are obsolete against MBTs of any kind if loaded with anything OTHER than PG-7VL or PG-7VR tandem-charge warheads. These suffer issues of their own, as they are extremely short-ranged and imprecise (the PG-7VR tandem-warhead is nearly ineffective beyond the range of a 9mm pistol, suffering extreme amounts of ballistic drop at very short range).

**Comment by SchwererKonigstiger** [comment]
Launchers are now in the town, along with plenty of ammo.
Also see #12
