### ISSUE TITLE
TAC Mod Issues

### ISSUE THREAD

**Issue by Yin-Yue** [SchwererKonigstiger/Missions#14]
Two to three people as of this writeup have had minor issues with the TAC mod. When handing out kits for testing, certain vests contained in the mod were not visible to certain people.

To recall specifics, when handing out a DMR kit to Aselia for testing, the kit was equipped with a TAC PMC vest Pointman(CY), the coyote-brown vest. This vest was not visible to Aselia, nor to Eogos when thrown on the ground. However, the black version of the very same vest was visible to both.
The same issue was repeated with the Medic vest from the same set, in Killjoy's case; again, switching from the brown to the black version of the vest caused it to be visible to everyone.

Also noteworthy is that despite the vests becoming visible to people on switching to a different color, the vests themselves were not available to these people within Arsenal - that is to say, the TAC PMC vests in general were available, but the Pointman and Medic sets within them were not.

Recommendations so far have been to delete the existing mod in the root folder, then re-extract from the .rar pack in an attempt to clear out any potentially corrupted files. Taking that note bit further, a full re-download may be necessary. I will locate the mod on Armaholic or upload my own files and provide a link should it become necessary.
Note: this is not to confirm that corrupted files are the case, though that would seem the likely assumption.

**Comment by SchwererKonigstiger** [comment]
Issue confined to mod load order.
Order of loading is as follows:
TRYK Uniforms
TAC Vests
Sparfell's TAC Vests Patch
Fix your load order and the problem *should* be resolved.

**Comment by Yin-Yue** [comment]
important note when changing load order: TAC Vests patch is located in the @CPC mod folder. Launcher will show it as CPC Factions.
