### ISSUE TITLE
Respawn Helicopter Won't Respawn

### ISSUE THREAD

**Issue by Eogos** [SchwererKonigstiger/Missions#5]
The insertion helicopter doesn't respawn if shot down on the map causing people to spawn at the destroyed heli until it's deleted. Even after deletion it still doesn't respawn and people just spawn at base.

**Comment by SchwererKonigstiger** [comment]
Don't shoot down the helo yourselves. It is invulnerable to enemy fire.
If it is destroyed, by feature, you respawn at base.
